# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alejandro Flores Lamas
# title: Senior Network System Administrator
email: alexfloreslamas@gmail.com
# website: https://github.com/alexfloreslamas

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  alexfloreslamas
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: alexfloreslamas
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-9637-2049

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# ----------------------------------#
# >>> A B O U T   S E C T I O N <<< #
# ----------------------------------#
about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Alejandro, a PhD in Computer Science. My research focuses on analysing and designing <mark>algorithms for graphs</mark>, with a recent interest in <mark>approximation algorithms</mark> and <mark>parameterised complexity</mark>. I am also involved in studying <mark>string constraint algorithms</mark>.

content:
    # --------------------------#
    # >>> E D U C A T I O N <<< #
    # --------------------------#
    
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # border: weak
        title: CICESE Research Center
        sub_title: PhD & MSc Computer Science
        caption: 2015 - 2018 & 2012 - 2014
        link: https://www.cicese.edu.mx/
        # quote: >
        #   [https://www.cicese.edu.mx/](https://www.cicese.edu.mx/)
        description: | # this will include new lines to allow paragraphs
          At CICESE, I acquired essential skills that have contributed significantly to my professional development, including time management, communication, and teamwork. My experience as a PhD student at CICESE was immensely gratifying and played a pivotal role in shaping my career.

          - *Supervisor:* [Dr. José Alberto Fernández-Zepeda.](https://dblp.org/pid/13/7045.html)

      - layout: left
        # border: weak
        title: Universidad Autónoma de Zacatecas
        sub_title: BEng Computer Engineering
        caption: 2007 - 2012
        link: https://www.uaz.edu.mx/
        # quote: >
        #   [https://www.cicese.edu.mx/](https://www.cicese.edu.mx/)
        description: | # this will include new lines to allow paragraphs
          While at the Autonomous University of Zacatecas, I gained proficiency in various programming languages, ranging from low-level machine language to high-level languages such as Java. Also, during my time at the University, I cultivated a keen interest in the analysis and design of algorithms.

      - layout: left
        # border: weak
        title: University of Manitoba
        caption: 2009 - 2010
        sub_title: Visiting student (BEng Computer Engineering)
        link: https://umanitoba.ca/
        # quote: >
        #   [https://www.cicese.edu.mx/](https://www.cicese.edu.mx/)
        description: | # this will include new lines to allow paragraphs
          At the University of Manitoba, I enriched my technical skills while acquiring valuable soft skills. I had the opportunity to immerse myself in diverse social settings, gaining insights into professional ethics and work culture. This experience helped me explore different career paths, making it a crucial milestone in my professional development journey.

      - layout: left
        # border: weak
        title: University of Belize
        caption: 2006 - 2007
        sub_title: ESL, English as Second Language
        link: https://www.ub.edu.bz/
        # quote: >
        #   [https://www.cicese.edu.mx/](https://www.cicese.edu.mx/)
        description: | # this will include new lines to allow paragraphs
          The University of Belize allowed me to experience, for the first time, an international and multicultural environment with a rich cultural exchange. This exposure broadened my understanding of the world and equipped me with skills to navigate and overcome language and communication barriers.

    # --------------------------------------------#
    # >>> P O S T D O C   E X P E R I E N C E <<< #
    # --------------------------------------------#
  - title: Postdoctoral experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Royal Holloway, University of London
        sub_title: Postdoctoral Research Assistant
        caption: 2020 - 2023
        link: https://www.royalholloway.ac.uk/
        # link_text: https://www.royalholloway.ac.uk/
        # quote: >
        #   Esse quam videri
        description: | # this will include new lines to allow paragraphs
            The focus of this project was on the handling of strings in software systems. Existing research relying on regular expressions to study strings often overlooks important features in modern programming languages. This project bridges such a gap by enhancing theoretical understanding and practical implementation.

            - *Supervisor:* [Prof. Matthew Hague.](https://www.cs.rhul.ac.uk/home/uxac009/)
            - *Project:* String Constraint Solving with Real-World Regular Expressions.
            - *Supported by:* The Engineering and Physical Sciences Research Council, EPSRC [EP/T00021X/1].
    
    # ----------------------------#
    # >>> E X P E R I E N C E <<< #
    # ----------------------------#
  - title: Experience
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## **Research:**
      - <mark>2020-2023</mark> *Postdoctoral research assistant*. Department of Computer Science, Royal Holloway, University of London, Centre for Programming Languages and Systems. United Kingdom.
      - <mark>2019-2019</mark> *Research associate*. The Artificial Intelligence Consortium of CONACYT Public Centers, CICESE Research Center. Mexico.
      - <mark>2015-2018</mark> *PhD in Computer Science*, CICESE Research Center, Ensenada, Baja California, Mexico.
      - <mark>2012-2014</mark> *MSc in Computer Science*, CICESE Research Center, Ensenada, Baja California, Mexico.
      
      ## **Teaching and mentoring** (undergraduate and masters' level)
      - <mark>2022-2022</mark> Royal Holloway, University of London. United Kingdom.
      - <mark>2016-2019</mark> CICESE Research Center. Mexico.
      - <mark>2010-2012</mark> CASE-UAZ. The Student Learning Services Center, The Autonomous University of Zacatecas, Mexico.
    
    
    # ------------------------#
    # >>> P R O J E C T S <<< #
    # ------------------------#
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: A dynamic programming algorithm for a maximum <i>s</i>-clique set on trees
        link: https://alexfloreslamas.github.io/maximum-s-clique-set-on-trees.io/
        # link_text: https://alexfloreslamas.github.io/maximum-s-clique-set-on-trees.io/
        additional_links:
          - title:  maximum-s-clique-set-on-trees
            icon: fab fa-github
            url: https://github.com/alexfloreslamas/maximum-s-clique-set-on-trees.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is ...
        description: | # this will include new lines to allow paragraphs
          Clique finding in networks is a fundamental problem graph problem. To overcome the limitations of strict cliques, a relaxed version called *s*-cliques is studied. The *s*-clique allows for greater flexibility in modelling relationships such as social concepts. Finding the largest *s*-clique in an arbitrary graph is computationally challenging. Here we propose a dynamic programming algorithm that efficiently solves such a problem on an *n*-vertex tree in *O*(*s⋅n*) time for *s*≥ 2, outperforming existing methods. This advancement paves the way for finding maximum *s*-cliques in less restrictive graphs. We use [Python](https://www.python.org/), [Pandas](https://pandas.pydata.org/), [YAML](https://yaml.org/) and [NetworkX](https://networkx.org/) for the project's scripts. We also provide a small set of artificial and real trees (along with corresponding credits) for experimentation.

      - layout: top-middle
        title: RegexFinder (Draft)
        link: https://www.cs.rhul.ac.uk/home/uhac208/Regex_Survey/RS.html
        # link_text: https://www.cs.rhul.ac.uk/home/uhac208/Regex_Survey/RS.html
        # additional_links:
        #   - title:  maximum-s-clique-set-on-trees
        #     icon: fab fa-github
        #     url: https://github.com/alexfloreslamas/maximum-s-clique-set-on-trees.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is ...
        description: | # this will include new lines to allow paragraphs
          This project involves a brief report on regular expressions (regex) within the [NPM package manager](https://www.npmjs.com/) for [JavaScript](https://www.javascript.com/). To extract the data, we developed a [Ruby](https://www.ruby-lang.org/en/) script called 'RegexFinder.rb'. The input can be either the NPM installation directory or a set of JavaScript files, and the output includes details about regex usage. The information is displayed on the screen and can be saved as markdown or PDF files.
    
    
    # ----------------------------#
    # >>> E X T R A   I N F O <<< #
    # ----------------------------#

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in ... some of my other interests and hobbies are:
  #     - item 
  #     - item
  #     - item

  #     Look at this cool image
  #     ![Trees](./images/landscape-trees.jpg "Trees")
    
    
    # ----------------------#
    # >>> C R E D I T S <<< #
    # ----------------------#
  - title: Credits
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **A modern simple static resume template and theme:** modern-resume-theme <a href="https://github.com/sproogen/modern-resume-theme" class="fa fa-github" aria-hidden="true"></a> by [James Grant](https://github.com/sproogen). 
      

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
