# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alejandro Flores Lamas
# title: Senior Network System Administrator
email: alexfloreslamas@gmail.com
# website: https://github.com/alexfloreslamas

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  alexfloreslamas
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: alexfloreslamas
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-9637-2049

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# ----------------------------------#
# >>> A B O U T   S E C T I O N <<< #
# ----------------------------------#
about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Alejandro, a PhD in Computer Science. My research focuses on analysing and designing <mark>algorithms for graphs</mark>, with a recent interest in <mark>approximation algorithms</mark> and <mark>parameterised complexity</mark>. I am also involved in studying <mark>string constraint algorithms</mark>.

content:
    # --------------------------#
    # >>> E D U C A T I O N <<< #
    # --------------------------#
    
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # border: weak
        title: CICESE Research Center
        sub_title: PhD & MSc Computer Science
        caption: 2015 - 2018 & 2012 - 2014
        link: https://www.cicese.edu.mx/
        # quote: >
        #   [https://www.cicese.edu.mx/](https://www.cicese.edu.mx/)
        description: | # this will include new lines to allow paragraphs
          At CICESE, I acquired essential skills that have contributed significantly to my professional development, including time management, communication, and teamwork. My experience as a PhD student at CICESE was immensely gratifying and played a pivotal role in shaping my career.

          - *Supervisor:* [Dr. José Alberto Fernández-Zepeda.](https://dblp.org/pid/13/7045.html)

      - layout: left
        # border: weak
        title: Universidad Autónoma de Zacatecas
        sub_title: BEng Computer Engineering
        caption: 2007 - 2012
        link: https://www.uaz.edu.mx/
        # quote: >
        #   [https://www.cicese.edu.mx/](https://www.cicese.edu.mx/)
        description: | # this will include new lines to allow paragraphs
          While at the Autonomous University of Zacatecas, I gained proficiency in various programming languages, ranging from low-level machine language to high-level languages such as Java. Also, during my time at the University, I cultivated a keen interest in the analysis and design of algorithms.

      - layout: left
        # border: weak
        title: University of Manitoba
        caption: 2009 - 2010
        sub_title: Visiting student (BEng Computer Engineering)
        link: https://umanitoba.ca/
        # quote: >
        #   [https://www.cicese.edu.mx/](https://www.cicese.edu.mx/)
        description: | # this will include new lines to allow paragraphs
          At the University of Manitoba, I enriched my technical skills while acquiring valuable soft skills. I had the opportunity to immerse myself in diverse social settings, gaining insights into professional ethics and work culture. This experience helped me explore different career paths, making it a crucial milestone in my professional development journey.

      - layout: left
        # border: weak
        title: University of Belize
        caption: 2006 - 2007
        sub_title: ESL, English as Second Language
        link: https://www.ub.edu.bz/
        # quote: >
        #   [https://www.cicese.edu.mx/](https://www.cicese.edu.mx/)
        description: | # this will include new lines to allow paragraphs
          The University of Belize allowed me to experience, for the first time, an international and multicultural environment with a rich cultural exchange. This exposure broadened my understanding of the world and equipped me with skills to navigate and overcome language and communication barriers.

    # ----------------------------#
    # >>> E X P E R I E N C E <<< #
    # ----------------------------#
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Royal Holloway, University of London
        sub_title: Postdoctoral Research Assistant
        caption: 2020 - 2023
        link: https://www.royalholloway.ac.uk/
        # link_text: https://www.royalholloway.ac.uk/
        # quote: >
        #   Esse quam videri
        description: | # this will include new lines to allow paragraphs
            The focus of this project was on the handling of strings in software systems. Existing research relying on regular expressions to study strings often overlooks important features in modern programming languages. This project bridges such a gap by enhancing theoretical understanding and practical implementation.

            - *Supervisor:* [Prof. Matthew Hague.](https://www.cs.rhul.ac.uk/home/uxac009/)
            - *Project:* String Constraint Solving with Real-World Regular Expressions.
            - *Supported by:* The Engineering and Physical Sciences Research Council, EPSRC [EP/T00021X/1].
            
      - layout: left
        title: Artificial Intelligence Consortium
        sub_title: Research Associate
        caption: 2019 - 2019
        description: | # this will include new lines to allow paragraphs
          The primary objective of the CONACYT Public Centers' Artificial Intelligence Consortium is to foster the development of highly skilled professionals in the field of Artificial Intelligence through applied research. The Consortium emphasises key areas such as urban mobility, healthcare, environmental risks, and mathematics for advancing Artificial Intelligence.
          
          - *Project:* Algorithms for Artificial Intelligence
          - *Supported by:* The Artificial Intelligence Consortium of CONACYT Public Centers, Mexico
        
      - layout: left
        title: CICESE Research Center
        sub_title: PhD in Computer Science
        caption: 2015 - 2018
        description: | # this will include new lines to allow paragraphs
          This project addresses the problem of finding a 2-packing set in some planar graphs in polynomial time, in both centralized and distributed environments. The main result is a parameterized algorithm that computes a maximum 2-packing set on a 1-outerplanar graph in linear time.
          
          - *Project:* Feasibility study to solve the maximum 2-packing set problem in polynomial time in outerplanar graphs (translated from Spanish)
          - *Supported by:* CONACYT, National Scholarship for doctoral studies, Mexico
        
      - layout: left
        title: CICESE Research Center
        sub_title: MSc in Computer Science
        caption: 2012 - 2014
        description: | # this will include new lines to allow paragraphs
          This work presents an approach to find a maximum 2-packing set in a cactus graph. The main result is an algorithm that decomposes the input graph into biconnected components to form a tree, then it solves each component individually and merges partial solutions to find such a set.
          
          - *Project:* An algorithm to find a maximum 2-packing set in a cactus graph (translated from Spanish)
          - *Supported by:* CONACYT, National Scholarship for master’s studies, Mexico

      - layout: left
        title: Teaching and mentoring
        sub_title: Undergraduate and Masters' level
        description: | # this will include new lines to allow paragraphs
          - <mark>2021-2022</mark> Royal Holloway, University of London. United Kingdom.
          - <mark>2022-2022</mark> CICESE Research Center (online co-teaching). Mexico.
          - <mark>2016-2019</mark> CICESE Research Center. Mexico.
          - <mark>2010-2012</mark> CASE-UAZ. The Student Learning Services Center, The Autonomous University of Zacatecas, Mexico.
    
    
    # --------------------------------------------#
    # >>> P R O J E C T S  &  M A T E R I A L <<< #
    # --------------------------------------------#
  - title: Projects & Material # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: A dynamic programming algorithm for a maximum <i>s</i>-clique set on trees
        link: https://alexfloreslamas.github.io/maximum-s-clique-set-on-trees.io/
        # link_text: https://alexfloreslamas.github.io/maximum-s-clique-set-on-trees.io/
        additional_links:
          - title:  maximum-s-clique-set-on-trees
            icon: fab fa-github
            url: https://github.com/alexfloreslamas/maximum-s-clique-set-on-trees.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is ...
        description: | # this will include new lines to allow paragraphs
          Clique finding in networks is a fundamental problem graph problem. To overcome the limitations of strict cliques, a relaxed version called *s*-cliques is studied. The *s*-clique allows for greater flexibility in modelling relationships such as social concepts. Finding the largest *s*-clique in an arbitrary graph is computationally challenging. Here we propose a dynamic programming algorithm that efficiently solves such a problem on an *n*-vertex tree in *O*(*s⋅n*) time for *s*≥ 2, outperforming existing methods. This advancement paves the way for finding maximum *s*-cliques in less restrictive graphs. We use [Python](https://www.python.org/), [Pandas](https://pandas.pydata.org/), [YAML](https://yaml.org/) and [NetworkX](https://networkx.org/) for the project's scripts. We also provide a small set of artificial and real trees (along with corresponding credits) for experimentation.

      - layout: top-middle
        title: RegexFinder (Draft)
        link: https://www.cs.rhul.ac.uk/home/uhac208/Regex_Survey/RS.html
        # link_text: https://www.cs.rhul.ac.uk/home/uhac208/Regex_Survey/RS.html
        # additional_links:
        #   - title:  maximum-s-clique-set-on-trees
        #     icon: fab fa-github
        #     url: https://github.com/alexfloreslamas/maximum-s-clique-set-on-trees.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is ...
        description: | # this will include new lines to allow paragraphs
          This project involves a brief report on regular expressions (regex) within the [NPM package manager](https://www.npmjs.com/) for [JavaScript](https://www.javascript.com/). To extract the data, we developed a [Ruby](https://www.ruby-lang.org/en/) script called 'RegexFinder.rb'. The input can be either the NPM installation directory or a set of JavaScript files, and the output includes details about regex usage. The information is displayed on the screen and can be saved as markdown or PDF files.

      - layout: top-middle
        title: Plantilla de tesis.tex
        link: https://biblioteca.cicese.mx/
        description: | # this will include new lines to allow paragraphs
          I was also briefly involved in creating CICESE's thesis template. See CICESE's [library webpage](https://biblioteca.cicese.mx/) and the README_Plantilla.txt file for more information.
    
    # --------------------------------#
    # >>> P U B L I C A T I O N S <<< #
    # --------------------------------#
    
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        # border: weak
        title: Journal
        sub_title: In preparation
        # caption: item
        # link: item
        # quote: >
        #   item
        description: | # this will include new lines to allow paragraphs
          José Alberto Fernández-Zepeda, **Alejandro Flores-Lamas**, Tadeo Alán Gutiérrez-Medina and Joel Antonio Trejo-Sánchez. *"A simple algorithm for decomposing geometric Halin graphs"*.  **2023**. *In preparation, to be submitted to*: [**Journal of Parallel and Distributed Computing.**](https://www.sciencedirect.com/journal/journal-of-parallel-and-distributed-computing)

      - layout: left
        # border: weak
        title: Brief announcement
        sub_title: Submitted
        # caption: item
        # link: item
        # quote: >
        #   item
        description: | # this will include new lines to allow paragraphs
          José Alberto Fernández-Zepeda, **Alejandro Flores-Lamas**, Candelaria E. Sansores-Pérez and Joel Antonio Trejo-Sánchez. *"Distributed approximation algorithm for the hub cover problem"*.  **2023**. *Submitted to:* [**The International Symposium on Distributed Computing (DISC).**](http://www.disc-conference.org/wp/disc2023/)

      - layout: left
        # border: weak
        title: Journal
        sub_title: Submitted
        # caption: item
        # link: item
        # quote: >
        #   item
        description: | # this will include new lines to allow paragraphs
          José Alberto Fernández-Zepeda, **Alejandro Flores-Lamas**, Matthew Hague and Joel Antonio Trejo-Sánchez. *"A dynamic programming algorithm for a maximum s-clique set on trees*. **2023**. *Submitted to:* [**Discrete Applied Mathematics.**](https://www.sciencedirect.com/journal/discrete-applied-mathematics)
      
      - layout: left
        title: Journal
        description: | # this will include new lines to allow paragraphs
          Joel Antonio Trejo-Sánchez, Francisco A. Madera-Ramírez, José Alberto Fernández-Zepeda, José Luis López-Martínez and **Alejandro Flores-Lamas** . *"A fast approximation algorithm for the maximum 2-packing set problem on planar graphs"*.  **2022**. *Available at*: [**Optimization Letters**](https://link.springer.com/article/10.1007/s11590-022-01939-w)

      - layout: left
        title: Proceedings
        description: | # this will include new lines to allow paragraphs
          Taolue Chen, **Alejandro Flores-Lamas**, Matthew Hague, Zhilei Han, Denghang Hu, Shuanglong Kan, Anthony W. Lin, Philipp Rümmer and Zhilin Wu. *"Solving string constraints with Regex-dependent functions through transducers with priorities and variables"*.  **2022**. *Available at*: [**Proceedings of the ACM on Programming Languages Vol. 6, Issue. POPL**](https://dl.acm.org/doi/abs/10.1145/3498707)

      - layout: left
        title: Journal
        description: | # this will include new lines to allow paragraphs
          **Alejandro Flores-Lamas**, José Alberto Fernández-Zepeda and Joel Antonio Trejo-Sánchez. *"A distributed algorithm for a maximal 2-packing set on Halin graphs"*.  **2020**. *Available at*: [**Journal of Parallel and Distributed Computing**](https://www.sciencedirect.com/science/article/abs/pii/S0743731519304459)

      - layout: left
        title: Doctoral thesis
        description: | # this will include new lines to allow paragraphs
          **Alejandro Flores-Lamas**. *"Estudio de factibilidad para resolver el problema 2-packing máximo en tiempo polinomial en grafos outerplanares"* (*"Feasibility study to solve the maximum 2-packing problem in polynomial time in outerplanar graphs"*, translated from Spanish), Doctoral dissertation.  **2018**. *Available at*: [**Biblioteca CICESE**, in Spanish.](https://biblioteca.cicese.mx/catalogo/tesis/ficha.php?id=25279)]
      
      - layout: left
        title: Proceedings
        description: | # this will include new lines to allow paragraphs
          Joel Antonio Trejo-Sánchez, Andrés Vela-Navarro, **Alejandro Flores-Lamas**, José Luis López-Martínez, Carlos Bermejo-Sabbagh and Nora Leticia Cuevas-Cuevas. *"Fast random cactus generation"*. **2018**. *Available at*: [**International Conference on Supercomputing in Mexico, ISUM 2018**](https://link.springer.com/chapter/10.1007/978-3-030-10448-1_12)

      - layout: left
        title: Journal
        description: | # this will include new lines to allow paragraphs
          **Alejandro Flores-Lamas**, José Alberto Fernández-Zepeda and Joel Antonio Trejo-Sánchez. *"Algorithm to find a maximum 2-packing set in a cactus"*. **2018**. *Available at*: [**Theoretical Computer Science**](https://www.sciencedirect.com/science/article/pii/S0304397517308605)
    # ----------------------------#
    # >>> E X T R A   I N F O <<< #
    # ----------------------------#

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <img src="./images/location.png"  width="25" height="25"> Mexico
      
      - <img src="./images/languages.png"  width="25" height="25">
        - Spanish, Mother tongue
        - English, C1. IELTS, 01 Feb 2020
        - German and French, Basic words and phrases only
        - I am willing to put in the time and effort required to learn a new language. 
      
      - <img src="./images/volunteer.png"  width="17" height="25"> In the past, I was actively involved in various volunteering endeavours:
        - <mark>2016-2018</mark> CICESE Open House
        - <mark>2007-2012</mark> Zacatecas International Folklore Festival "Gustavo Vaquera Contreras"
        - <mark>2009</mark> International year of astronomy
        - <mark>2004, 2005, 2012</mark> Good Vision to Learn Better
        - <mark>2004-2005</mark> SEMARNAT, Secretariat of Environment and Natural Resources, Mexico
        - <mark>2003-2005</mark> Zacatecas Food bank
        - <mark>2005</mark> Zacatecas Street Theater Festival

    # Look at this cool image
    # ![Trees](./images/landscape-trees.jpg "Trees")
    
    
    # ----------------------#
    # >>> C R E D I T S <<< #
    # ----------------------#
  - title: Credits
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **A modern simple static resume template and theme:** modern-resume-theme <a href="https://github.com/sproogen/modern-resume-theme" class="fa fa-github" aria-hidden="true"></a> by [James Grant](https://github.com/sproogen). 
      

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
